# Future Work

Initially, the project team aimed to develop a guiding tool for Nobel Prize awarding institutions as well as academic professionals that would allow them to explore historic data, identify key insights, and improve their decision making abilities. The team was able to accomplish most of the objectives set for the Nobel Prize awarding institutions using the developed shiny app, however, the goals drafted for academic professionals were treated as out of the project scope due to limitations imposed by the dataset. In particular, the team struggled to merge the two available dataset, nobel_winners and nobe_winners_publications, as the unique laureate id were different in both datasets. 

The objectives laid out by the project team for academic professionals aimed to increase their likelihood of winning the nobel prize by studying the journey of historic winners. The app would enable users to study the path adopted by historic winners in their respective  fields, which would provide details on their life choices as well as academic performance prior to winning the nobel prize. In this case, the app will provide information like the top universities in the selected field, average number of publications, average academic performance, and others,  based on the parameters selected or filters applied by the user. future work should aim to develop a decision making guide for academic professional by merging the details from the two datasets. This tool will allow users to evaluate their current performance, estimate the required efforts, and predict the likelihood of winning based on the historic data.

Additionally, we would want to make performance improvements to the application. In order to improve the overall performance of the application, we would like to utilize caching of the plots to decrease the loading time. Furthermore, we could utilize the shinyloadtest package to analyze the performance of the app and continue to streamline its performance. Aesthetically, the interface could be improved as well to help increase the usability of the application. For example, making sure that plots are being properly formatted when filtering is being applied and so forth. It is important to always be evaluating the performance and usability of the application.

